export const NUMBER_OF_ADMIN = 2;

export const NUMBER_OF_CUSTOMER = 10;

export const NUMBER_OF_ORDERS = 2;

export const MIN_CARGO_QUANTITY = 1;
export const MAX_CARGO_QUANTITY = 10;

export const MAX_NUMBER_OF_EMPLOYEES_PER_TRANSACTION_POINT = 10;
export const MAX_NUMBER_OF_EMPLOYEES_PER_ASSEMBLY_POINT = 40;

export const MAX_TRANSACTION_POINT_PER_ASSEMBLY_POINT = 10;
export const MIN_TRANSACTION_POINT_PER_ASSEMBLY_POINT = 2;

export const MAX_DAYS_TO_RECEIVE = 100;
